### ISSUE TITLE
Add support for images with reference-style URLs

### ISSUE THREAD

**Issue by robinmetral** [paulrobertlloyd/jekyll-figure#4]
Right now jekyll-figure strips `<p>` markup surrounding images with inline-style URLs:
```markdown
![Image](/path/to/image.jpg)
```
It would be great to add support for images with reference-style URLs:
```markdown
![Image][image-path]

[image-path]: /path/to/image.jpg
```

**Comment by paulrobertlloyd** [comment]
Hi @robinmetral, sorry it’s taken a while to respond to your issue. However, I don’t believe your issue is related to this plugin. Kramdown, the Markdown parser used by Jekyll, [doesn’t support the reference style syntax for images](https://kramdown.gettalong.org/quickref.html#links-and-images) (and this plugin defers to that to parse any Markdown you provide).

Closing, but please reopen if you feel I have misunderstood your issue.
